#!/usr/bin/env python
"""Generate the paper's LaTeX tables from the derived data, so every number in
the manuscript traces to a script rather than a hand transcription.

Emits into ``paper/tables/``:

* ``uplift.tex``        -- Table 1: ratio-of-means intervals for the bio-uplift
                           trial, every reading x method (from uplift_readings.csv).
* ``audit.tex``         -- Table 2: the nine threshold-vs-interval rows, with the
                           +/-1-count and clustering columns (from audited.csv).
* ``census.tex``        -- Appendix census longtable, parsed from census_full.md.
* ``census_counts.tex`` -- \\newcommand macros with the EXACT census counts, so the
                           main-text summary cites auditable numbers, not "~60".

Run after uplift_analysis.py and run_audit.py (which write the derived CSVs).
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DERIVED = ROOT / "data" / "derived"
CENSUS_MD = ROOT / "data" / "raw" / "census_full.md"
TABLES = ROOT / "paper" / "tables"


# --------------------------------------------------------------------------- #
# LaTeX escaping for free-text cells (census carries lots of unicode/math).
# --------------------------------------------------------------------------- #
_UNICODE = [
    ("×", r"$\times$"), ("≥", r"$\ge$"), ("≤", r"$\le$"), ("→", r"$\to$"),
    ("±", r"$\pm$"), ("≈", r"$\approx$"), ("–", "--"), ("—", "---"),
    ("’", "'"), ("‘", "'"), ("“", "``"), ("”", "''"),
    ("§", r"\S{}"), ("<", r"$<$"), (">", r"$>$"), ("~", r"$\sim$"),
]


def latex_escape(text: str) -> str:
    text = text.strip()
    # Strip Markdown bold markers carried over from the source cells (e.g. the
    # emphasised "**± 12.9%**" UK AISI margins) -- they are source emphasis, not
    # table content.
    text = text.replace("**", "")
    # Protect specials first (order matters: backslash before others).
    text = text.replace("\\", r"\textbackslash{}")
    for ch in ("&", "%", "#", "_", "{", "}"):
        text = text.replace(ch, "\\" + ch)
    for uni, rep in _UNICODE:
        text = text.replace(uni, rep)
    return text


# --------------------------------------------------------------------------- #
# Table 1: uplift readings x methods.
# --------------------------------------------------------------------------- #
def _ci_str(lo, hi):
    # One decimal place: propagating the card's integer-rounded inputs moves each
    # endpoint by 0.1--0.4x, so a second decimal would be false precision (only the
    # binary straddle-2.8x verdict is robust to the input rounding).
    def f(x):
        if x == "+inf":
            return r"$\infty$"
        if x == "-inf":
            return r"$-\infty$"
        if x == "n/a":
            return "n/a"
        return f"{float(x):.1f}$\\times$"
    return f"{f(lo)}--{f(hi)}"


def build_uplift_table():
    src = DERIVED / "uplift_readings.csv"
    rows = list(csv.DictReader(src.open()))
    # One display row per (reading, arm): Fieller | delta | bootstrap, + verdict.
    keyed = {}
    order = []
    for r in rows:
        k = (r["reading"], r["arm_n"])
        if k not in keyed:
            keyed[k] = {}
            order.append(k)
        keyed[k][r["method"]] = r

    body = []
    for (reading, arm) in order:
        methods = keyed[(reading, arm)]
        # Headline Fieller: the small-sample t(df=n-1) interval where a per-arm n
        # is defined (the SD reading); the n-free readings (SE, CI half-width) have
        # no df and fall back to the normal-z construction.
        fie = methods.get("fieller_t") or methods.get("fieller_z")
        dlt = methods.get("delta_z")
        boo = methods.get("bootstrap")
        fie_s = _ci_str(fie["low"], fie["high"])
        if fie["kind"] == "unbounded_above":
            fie_s += r"\,(unbounded)"
        del_s = _ci_str(dlt["low"], dlt["high"])
        boo_s = _ci_str(boo["low"], boo["high"]) if boo["kind"] != "infeasible" else "infeasible"
        # verdict vs 2.8x / 5x, taken from the Fieller row (the headline method)
        vparts = [r"straddles $2.8\times$" if fie["straddles_2.8x"] == "True"
                  else r"resolves $2.8\times$"]
        if fie["reaches_5x"] == "True":
            vparts.append(r"reaches $5\times$")
        verdict = "; ".join(vparts)
        arm_lbl = arm if arm != "n-free" else "$n$-free"
        body.append(
            f"        {latex_escape(reading)} & {arm_lbl} & {fie_s} & {del_s} & "
            f"{boo_s} & {verdict} \\\\"
        )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{table}[t]
    \centering
    \small
    \begin{tabular}{llllll}
        \toprule
        reading of ``$\pm 13\%$'' & arm & Fieller 95\% set & delta 95\% CI & bootstrap 95\% CI & verdict \\
        \midrule
""" + "\n".join(body) + r"""
        \bottomrule
    \end{tabular}
    \caption{Uplift-ratio interval for the Opus~4 bio-uplift trial
    ($0.63/0.25 = 2.52\times$; the card reports $2.53\times$ from unrounded means),
    computed as a ratio of two arm means propagating the card's unlabelled
    ``$\pm 13\%$'' dispersion under every admissible reading. Fieller (headline)
    inverts the exact test, at the small-sample $t(\mathrm{df}=n-1)$ critical value
    where a per-arm $n$ is defined (the SD reading) and at the normal $z$ for the
    $n$-free readings; the delta method is a linearisation check that stays finite
    even when the exact set is unbounded; the parametric bootstrap draws
    scaled-Beta arms on $[0,100]$. \textbf{Every reading straddles the
    $2.8\times$ acceptable line}; under the most conventional (SD) reading the set
    is bounded and also excludes the $5\times$ significant-risk line. Endpoints are
    given to one decimal because propagating the card's integer-rounded inputs
    shifts each by $0.1$--$0.4\times$, so only the binary straddle verdict is
    rounding-robust. Under the standard-error reading the control mean sits just
    below significance at 95\% ($25/13 \approx 1.92 < 1.96$), so the Fieller set is
    then \emph{unbounded above} and the finite delta interval is a linearisation
    artifact; this prong is conditional on that reading and on the inputs' rounding
    (a control mean of $25.5$ or a dispersion of $12.7$ would bound it), whereas the
    straddle holds at every corner.}
    \label{tab:uplift}
\end{table}
"""
    (TABLES / "uplift.tex").write_text(tex)
    return len(order)


# --------------------------------------------------------------------------- #
# Table 2: the nine audited rows.
# --------------------------------------------------------------------------- #
_MODEL_ORDER = None  # keep CSV order


def _verdict_short(v):
    if v.startswith("CANNOT"):
        return r"\textbf{CANNOT RESOLVE}"
    if "above" in v:
        return "resolved above"
    if "below" in v:
        return "resolved below"
    return latex_escape(v)


def build_audit_table(census_id_map=None):
    census_id_map = census_id_map or {}
    src = DERIVED / "audited.csv"
    rows = list(csv.DictReader(src.open()))
    body = []
    for r in rows:
        cd = r["critical_deff"]
        icc = r["critical_icc"]
        if r["assumed_m"] == "":
            cd_str = f"{cd} (single-task)" if cd else "---"
        elif cd:
            cd_str = f"{cd} ({icc}@{r['assumed_m']})"
        else:
            cd_str = "---"
        # +/-1-count sensitivity marker
        pm1 = r"\checkmark" if r["count_sensitive"] == "1" else "---"
        # convention tier marker for SWE-bench
        tier = r"$\dagger$" if r.get("convention_sensitive") == "1" else ""
        eval_name = {
            "swebench_hard": "SWE-bench hard",
            "metr_dedup": "METR dedup",
            "bioweapons_knowledge": "Bioweapons knowl.",
        }.get(r["capability"], r["capability"])
        # Cross-reference the row's ID in the full census (Table 4).
        cid = census_id_map.get((r["capability"], r["model"]))
        if cid:
            eval_name = f"{eval_name} ({cid})"
        ci = f"{float(r['ci_low']):.2f}--{float(r['ci_high']):.2f}"
        body.append(
            f"        {eval_name} & {latex_escape(r['model'])} & {r['n']} & "
            f"{float(r['score']):.2f} & {ci} & {float(r['threshold']):.2f} & "
            f"{_verdict_short(r['verdict'])}{tier} & {r['required_n']} & "
            f"{float(r['prob_above']):.3f} & {pm1} & {cd_str} \\\\"
        )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{table}[t]
    \centering
    \scriptsize
    \resizebox{\textwidth}{!}{%
    \begin{tabular}{llccccllcccl}
        \toprule
        eval & model & $n$ & $\hat p$ & 95\% CI & $\tau$ & verdict & $n_{\mathrm{req}}$ & $P(p>\tau)$ & $\pm$1 & crit.\ DEFF (ICC@$m$) \\
        \midrule
""" + "\n".join(body) + r"""
        \bottomrule
    \end{tabular}%
    }
    \caption{Bernoulli audit of the nine rows reporting an integer pass count
    against a numeric threshold on that proportion. Five of nine cannot resolve their
    threshold at 95\% (Wilson); robustness of this count to the interval
    construction and confidence level is reported in \Cref{app:robustness}.
    The Beta-Binomial posterior $P(p>\tau)$ agrees with the Wilson
    verdict on every row. \textbf{$\pm$1} flags a verdict that flips if the
    reconstructed pass count moves by one (Wilson, 95\%). Verdicts marked $\dagger$ are
    convention-dependent: they cannot resolve under the task-generalisation $n$
    but resolve below under the run-generalisation convention
    ($n = \text{tasks}\times10$ runs); the task-level estimand is our headline (\Cref{app:robustness}).
    Critical DEFF is the smallest design effect at which the interval begins to
    straddle; the parenthesised ICC is its translation at cluster size $m$. The
    code after each eval name (e.g.\ ``(A5)'') is that row's ID in the full
    census, \Cref{tab:census}, where these rows are shaded.}
    \label{tab:audit}
\end{table}
"""
    (TABLES / "audit.tex").write_text(tex)
    return len(rows)


# --------------------------------------------------------------------------- #
# Census: parse the markdown pipe tables, emit longtable + exact-count macros.
# --------------------------------------------------------------------------- #
FRAMEWORK_OF_HEADER = [
    ("Anthropic (RSP", "Anthropic-RSP"),
    ("OpenAI (Preparedness", "OpenAI-PF"),
    ("Google DeepMind (FSF", "GDM-FSF"),
    ("Third-party", "3rd-party"),
    ("OpenAI GPT-5.5", "OpenAI-PF"),
    ("OpenAI GPT-5.6", "OpenAI-PF"),
    ("Anthropic Opus 4.5", "Anthropic-RSP"),
    ("Google DeepMind Gemini 3", "GDM-FSF"),
]


def _framework_for(header: str):
    for needle, fw in FRAMEWORK_OF_HEADER:
        if needle in header:
            return fw
    return None


def _has_uncertainty(ci_cell: str) -> bool:
    c = ci_cell.strip().lower()
    if c in ("none", "n/a", "none (figure)", ""):
        return False
    if "no ci" in c:
        return False
    return ("±" in ci_cell) or ("ci" in c) or ("credible" in c) or (
        "bootstrap" in c) or ("error bar" in c) or ("margin" in c)


def _is_proper_interval(ci_cell: str) -> bool:
    """A usable interval (CI / credible / bootstrap / error bar), as opposed to a
    bare, unlabelled '± x%' dispersion."""
    c = ci_cell.strip().lower()
    if "no ci" in c:
        return False
    return ("ci" in c) or ("credible" in c) or ("bootstrap" in c) or ("error bar" in c)


def parse_census():
    lines = CENSUS_MD.read_text().splitlines()
    generation = "primary"
    framework = None
    parsed = []  # dicts: generation, framework, domain, model, threshold, n, score, ci, direction, citation
    for line in lines:
        if line.startswith("# Post-2025 generation"):
            generation = "post2025"
            continue
        if line.startswith("## "):
            framework = _framework_for(line[3:])
            continue
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 8:
            continue
        if cells[0].lower() in ("domain", ":---", "---") or set(cells[0]) <= {"-", ":", " "}:
            continue
        if all(set(c) <= {"-", ":", " "} for c in cells):
            continue  # separator row
        domain, model, threshold, n, score, ci, direction, citation = cells
        if framework is None:
            continue
        parsed.append({
            "generation": generation, "framework": framework,
            "domain": domain, "model": model, "threshold": threshold,
            "n": n, "score": score, "ci": ci, "direction": direction,
            "citation": citation,
        })
    return parsed


# --------------------------------------------------------------------------- #
# Cross-reference between the census (Table 4) and the audit (Table 2). The
# audit's nine rows are a subset of the census; we tag those census rows so
# build_census can shade them and hand each a stable ID that build_audit_table
# then prints, making the mapping between the two tables explicit.
# --------------------------------------------------------------------------- #
_FRAMEWORK_LETTER = {
    "Anthropic": "A", "OpenAI": "O", "DeepMind": "D", "3rd-party": "T",
}


def audit_capability(row):
    """Return the audit capability slug for a census row that is one of the nine
    audited rows, else None. Only Anthropic rows are auditable; the domain text
    varies (``SWE-bench Verified (hard)`` vs ``SWE-bench hard``), so match on the
    domain prefix rather than the exact string."""
    if row["framework"] != "Anthropic-RSP":
        return None
    d = row["domain"]
    if d.startswith("Autonomy SWE-bench"):
        return "swebench_hard"
    if d.startswith("Autonomy METR data-dedup"):
        return "metr_dedup"
    if d.startswith("CBRN bioweapons knowledge"):
        return "bioweapons_knowledge"
    return None


def _audited_models():
    """capability -> set of model names actually audited (from audited.csv)."""
    out = {}
    for r in csv.DictReader((DERIVED / "audited.csv").open()):
        out.setdefault(r["capability"], set()).add(r["model"])
    return out


def build_census(parsed):
    primary = [r for r in parsed if r["generation"] == "primary"]
    post = [r for r in parsed if r["generation"] == "post2025"]

    def counts(rows):
        # A row "reports a concrete sample size" iff its n cell contains a
        # digit; the only n-absent pattern in the census is a bare "NOT REPORTED".
        with_n = sum(1 for r in rows if re.search(r"\d", r["n"]))
        unc = sum(1 for r in rows if _has_uncertainty(r["ci"]))
        interval = sum(1 for r in rows if _is_proper_interval(r["ci"]))
        bare_pm = unc - interval
        return len(rows), with_n, len(rows) - with_n, unc, interval, bare_pm

    # Headline macros are computed over the FULL census (primary + post-2025),
    # so the paper's census covers the whole record through the June 2026 cards.
    # \CensusPostRows retains the post-2025 sub-count for the trend narrative.
    p_total, p_n, p_non, p_unc, p_int, p_pm = counts(parsed)

    macros = rf"""% GENERATED by scripts/make_tables.py -- exact census counts.
\newcommand{{\CensusTotal}}{{{p_total}}}
\newcommand{{\CensusWithN}}{{{p_n}}}
\newcommand{{\CensusNoN}}{{{p_non}}}
\newcommand{{\CensusUncertainty}}{{{p_unc}}}
\newcommand{{\CensusNoUncertainty}}{{{p_total - p_unc}}}
\newcommand{{\CensusInterval}}{{{p_int}}}
\newcommand{{\CensusBarePm}}{{{p_pm}}}
\newcommand{{\CensusPostRows}}{{{len(post)}}}
"""
    (TABLES / "census_counts.tex").write_text(macros)

    # Longtable of the FULL census (primary generation, then post-2025 rows in
    # file order, grouped by the existing framework column).
    header_map = {
        "Anthropic-RSP": "Anthropic", "OpenAI-PF": "OpenAI",
        "GDM-FSF": "DeepMind", "3rd-party": "3rd-party",
    }
    audited = _audited_models()
    counters = {}      # framework letter -> running count
    id_map = {}        # (capability, model) -> census row ID, for the audit table
    body = []
    for r in parsed:
        display_fw = header_map.get(r["framework"], r["framework"])
        letter = _FRAMEWORK_LETTER.get(display_fw, "X")
        counters[letter] = counters.get(letter, 0) + 1
        row_id = f"{letter}{counters[letter]}"

        # Is this one of the nine audited rows? Match capability + model, where a
        # census cell can bundle models ("Opus 4 / Sonnet 4"); tag the row and
        # register the ID under each audited model it covers.
        cap = audit_capability(r)
        is_audited = False
        if cap is not None:
            audited_here = audited.get(cap, set())
            for m in (t.strip() for t in r["model"].split("/")):
                if m in audited_here:
                    is_audited = True
                    id_map[(cap, m)] = row_id

        prefix = r"\rowcolor{auditrow} " if is_audited else ""
        body.append(
            prefix + "  " + " & ".join([
                row_id,
                display_fw,
                latex_escape(r["domain"]),
                latex_escape(r["model"]),
                latex_escape(r["threshold"]),
                latex_escape(r["n"]),
                latex_escape(r["score"]),
                latex_escape(r["ci"]),
                latex_escape(r["citation"]),
            ]) + r" \\"
        )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{small}
\begin{longtable}{p{0.7cm}p{1.4cm}p{2.4cm}p{1.5cm}p{2.2cm}p{1.2cm}p{1.7cm}p{1.5cm}p{1.9cm}}
\caption{Full census of governance-relevant evaluation rows, spanning the
Claude~4 / Gemini~2.5 / GPT-4.x generation through the GPT-5.6~Preview card of
June 2026, parsed from \texttt{data/raw/census\_full.md}. ``uncert.'' reproduces
the source's uncertainty cell verbatim; most rows report none. Each row carries
an ID (framework letter + running number); \colorbox{auditrow}{shaded} rows are
the nine audited in \Cref{sec:audit}, and their IDs appear beside the eval names
in \Cref{tab:audit}.}
\label{tab:census}\\
\toprule
ID & framework & domain & model & threshold & $n$ & score & uncert. & citation \\
\midrule
\endfirsthead
\multicolumn{9}{c}{\tablename\ \thetable\ -- continued}\\
\toprule
ID & framework & domain & model & threshold & $n$ & score & uncert. & citation \\
\midrule
\endhead
\midrule \multicolumn{9}{r}{continued on next page}\\
\endfoot
\bottomrule
\endlastfoot
""" + "\n".join(body) + r"""
\end{longtable}
\end{small}
"""
    (TABLES / "census.tex").write_text(tex)
    return {
        "total": p_total, "with_n": p_n, "no_n": p_non,
        "uncertainty": p_unc, "interval": p_int, "bare_pm": p_pm,
        "post_rows": len(post), "id_map": id_map,
    }


def main():
    TABLES.mkdir(parents=True, exist_ok=True)
    nu = build_uplift_table()
    # Census first: it assigns the row IDs that the audit table cross-references.
    parsed = parse_census()
    cinfo = build_census(parsed)
    na = build_audit_table(cinfo["id_map"])
    print(f"uplift.tex: {nu} reading-rows")
    print(f"audit.tex:  {na} rows")
    print(f"census.tex: {cinfo['total']} rows (full census; "
          f"{cinfo['post_rows']} from the post-2025 generation)")
    print(f"census counts (full): total={cinfo['total']}, "
          f"with n={cinfo['with_n']}, no n={cinfo['no_n']}, "
          f"any uncertainty={cinfo['uncertainty']} "
          f"(proper interval={cinfo['interval']}, bare ±={cinfo['bare_pm']})")
    print(f"wrote tables into {TABLES}")


if __name__ == "__main__":
    main()
