#!/usr/bin/env python
"""Generate the paper's LaTeX tables from the derived data, so every number in
the manuscript traces to a script rather than a hand transcription.

Emits into ``paper/tables/``:

* ``uplift.tex``        -- Table 1: ratio-of-means intervals for the bio-uplift
                           trial, every reading x method (from uplift_readings.csv).
* ``audit.tex``         -- Table 2: threshold-vs-bound rows, with the
                           +/-1-count and clustering columns (from audited.csv).
* ``census.tex``        -- Appendix corpus longtable, parsed from census_records.csv.
* ``census_counts.tex`` -- \\newcommand macros with the EXACT census counts, so the
                           main-text summary cites auditable numbers, not "~60".
* ``census_sensitivity.tex`` -- Primary-vs-screened coding sensitivity.

Run after uplift_analysis.py and run_audit.py (which write the derived CSVs).
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DERIVED = ROOT / "data" / "derived"
CENSUS_CSV = ROOT / "data" / "raw" / "census_records.csv"
TABLES = ROOT / "paper" / "tables"


# --------------------------------------------------------------------------- #
# LaTeX escaping for free-text cells (census carries lots of unicode/math).
# --------------------------------------------------------------------------- #
_UNICODE = [
    ("×", r"$\times$"), ("≥", r"$\ge$"), ("≤", r"$\le$"), ("→", r"$\to$"),
    ("±", r"$\pm$"), ("≈", r"$\approx$"), ("–", "--"), ("—", "---"),
    ("’", "'"), ("‘", "'"), ("“", "``"), ("”", "''"),
    ("§", r"\S{}"), ("<", r"$<$"), (">", r"$>$"), ("~", r"$\sim$"),
]


def latex_escape(text: str) -> str:
    text = text.strip()
    # Strip Markdown bold markers carried over from the source cells (e.g. the
    # emphasised "**± 12.9%**" UK AISI margins) -- they are source emphasis, not
    # table content.
    text = text.replace("**", "")
    # Protect specials first (order matters: backslash before others).
    text = text.replace("\\", r"\textbackslash{}")
    for ch in ("&", "%", "#", "_", "{", "}"):
        text = text.replace(ch, "\\" + ch)
    for uni, rep in _UNICODE:
        text = text.replace(uni, rep)
    return text


# --------------------------------------------------------------------------- #
# Table 1: uplift readings x methods.
# --------------------------------------------------------------------------- #
def _ci_str(lo, hi):
    # One decimal place: propagating the card's integer-rounded inputs moves each
    # endpoint by 0.1--0.4x, so a second decimal would be false precision (only the
    # binary straddle-2.8x verdict is robust to the input rounding).
    def f(x):
        if x == "+inf":
            return r"$\infty$"
        if x == "-inf":
            return r"$-\infty$"
        if x == "n/a":
            return "n/a"
        return f"{float(x):.1f}$\\times$"
    return f"{f(lo)}--{f(hi)}"


def build_uplift_table():
    src = DERIVED / "uplift_readings.csv"
    rows = list(csv.DictReader(src.open()))
    # One display row per (reading, arm): Fieller | delta | bootstrap, + verdict.
    keyed = {}
    order = []
    for r in rows:
        k = (r["reading"], r["arm_n"])
        if k not in keyed:
            keyed[k] = {}
            order.append(k)
        keyed[k][r["method"]] = r

    body = []
    for (reading, arm) in order:
        methods = keyed[(reading, arm)]
        # Headline Fieller: Welch-t where arm sizes are defined; normal-z for
        # the two n-free interpretations.
        fie = methods.get("fieller_t") or methods.get("fieller_z")
        dlt = methods.get("delta_t") or methods.get("delta_z")
        boo = methods.get("bootstrap")
        fie_s = _ci_str(fie["low"], fie["high"])
        if fie["kind"] == "unbounded_above":
            fie_s += r"\,(unbounded)"
        del_s = _ci_str(dlt["low"], dlt["high"])
        boo_s = (
            _ci_str(boo["low"], boo["high"])
            if boo["kind"] == "bounded" else "not identified"
        )
        # verdict vs 2.8x / 5x, taken from the Fieller row (the headline method)
        vparts = [r"straddles $2.8\times$" if fie["straddles_2.8x"] == "True"
                  else r"resolves $2.8\times$"]
        if fie["reaches_5x"] == "True":
            vparts.append(r"reaches $5\times$")
        verdict = "; ".join(vparts)
        arm_lbl = arm if arm != "n-free" else "$n$-free"
        body.append(
            f"        {latex_escape(reading)} & {arm_lbl} & {fie_s} & {del_s} & "
            f"{boo_s} & {verdict} \\\\"
        )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{table}[t]
    \centering
    \small
    \resizebox{\textwidth}{!}{%
    \begin{tabular}{llllll}
        \toprule
        reading of ``$\pm 13\%$'' & $n_C/n_T$ & Fieller 95\% set & delta 95\% CI & bootstrap 95\% CI & verdict \\
        \midrule
""" + "\n".join(body) + r"""
        \bottomrule
    \end{tabular}
    }
    \caption{Uplift-ratio interval for the Opus~4 bio-uplift trial
    ($0.63/0.25 = 2.52\times$; the card reports $2.53\times$ from unrounded means),
    computed as a ratio of two arm means propagating the card's unlabelled
    ``$\pm 13\%$'' dispersion under the three conventional readings considered.
    The SD rows enumerate all nine ordered arm-size combinations allowed by the
    reported 8--10 participants per arm and use Welch--Satterthwaite degrees of
    freedom; the $n$-free rows use a normal critical value. The participant-level
    bootstrap is not identified for the $n$-free readings. \textbf{Every row
    straddles the $2.8\times$ acceptable line}; under the SD reading the set is
    bounded and excludes the $5\times$ significant-risk line. Endpoints are
    given to one decimal because propagating the card's integer-rounded inputs
    shifts each by $0.1$--$0.4\times$, so only the binary straddle verdict is
    rounding-robust. Under the standard-error reading the control mean sits just
    below significance at 95\% ($25/13 \approx 1.92 < 1.96$), so the Fieller set is
    then \emph{unbounded above} and the finite delta interval is a linearisation
    artifact. On the whole real line that Fieller set is
    $(-\infty,-131.2]\cup[1.05,\infty)$; the table displays $[1.05,\infty)$ only
    after intersecting with the substantively justified nonnegative-ratio
    parameter space.}
    \label{tab:uplift}
\end{table}
"""
    (TABLES / "uplift.tex").write_text(tex)
    return len(order)


# --------------------------------------------------------------------------- #
# Table 2: the ten model-level audited rows.
# --------------------------------------------------------------------------- #
_MODEL_ORDER = None  # keep CSV order


def _verdict_short(v):
    if v.startswith("CANNOT"):
        return r"\textbf{CANNOT RESOLVE}"
    if "above" in v:
        return "resolved above"
    if "below" in v:
        return "resolved below"
    return latex_escape(v)


def build_audit_table(census_id_map=None):
    census_id_map = census_id_map or {}
    src = DERIVED / "audited.csv"
    rows = list(csv.DictReader(src.open()))
    body = []
    for r in rows:
        cd = r["critical_deff"]
        if r["assumed_m"] == "":
            cd_str = "n/a"
        elif cd:
            cd_str = (
                f"{cd} ({r['critical_icc_m5']}/"
                f"{r['critical_icc_m10']}/{r['critical_icc_m20']})"
            )
        else:
            cd_str = "---"
        # +/-1-count sensitivity marker
        pm1 = r"\checkmark" if r["count_sensitive"] == "1" else "---"
        eval_name = {
            "swebench_hard": "SWE-bench hard",
            "metr_dedup": "METR dedup",
            "bioweapons_knowledge": "Bioweapons knowl.",
        }.get(r["capability"], r["capability"])
        # Cross-reference the row's ID in the full census (Table 4).
        cid = r.get("record_id") or census_id_map.get((r["capability"], r["model"]))
        if cid:
            eval_name = f"{eval_name} ({cid})"
        ci = f"{float(r['directional_low']):.2f}--{float(r['directional_high']):.2f}"
        two_sided = "unresolved" if r["unresolved_two_sided"] == "1" else "resolved"
        body.append(
            f"        {eval_name} & {latex_escape(r['model'])} & {r['n']} & "
            f"{float(r['score']):.2f} & {ci} & {float(r['threshold']):.2f} & "
            f"{_verdict_short(r['verdict'])} & {two_sided} & {r['required_n']} & "
            f"{float(r['prob_above']):.3f} & {pm1} & {cd_str} \\\\"
        )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{table}[t]
    \centering
    \scriptsize
    \resizebox{\textwidth}{!}{%
    \begin{tabular}{llcccclllccl}
        \toprule
        eval & model & $n$ & $\hat p$ & one-sided 95\% bounds & $\tau$ & primary verdict & two-sided & $n_{\mathrm{req}}$ & $P(p>\tau)$ & $\pm$1 & crit.\ DEFF (ICC@$m=5/10/20$) \\
        \midrule
""" + "\n".join(body) + r"""
        \bottomrule
    \end{tabular}%
    }
    \caption{Conditional IID-Bernoulli audit of ten model-level results. The
    deployment-aligned primary rule uses the one-sided 95\% Wilson bound in the
    observed direction. Two of six direct-count rows are unresolved. For the four
    SWE-bench rows, two are unresolved under the task-level convention shown and
    one under the run-level sensitivity ($n=\text{tasks}\times10$). The central
    two-sided 95\% sensitivity leaves five of ten task-level rows unresolved (three
    of ten if the SWE rows use run-level denominators). $P(p>\tau)$ is the
    Beta posterior probability under a uniform prior. \textbf{$\pm$1} flags a
    primary verdict that flips if a reconstructed count moves by one.
    Critical DEFF is the smallest design effect at which the directional bounds begin to
    straddle; parenthesised values translate it to ICC at $m=5,10,20$. ``n/a''
    marks METR repeated-run rows, for which item clustering is inapplicable (not
    evidence of independence). The
    code after each eval name (e.g.\ ``(A5)'') is that row's ID in the full
    census, \Cref{tab:census}, where these rows are shaded.}
    \label{tab:audit}
\end{table}
"""
    (TABLES / "audit.tex").write_text(tex)
    return len(rows)


# --------------------------------------------------------------------------- #
# Census: explicit record coding -> longtable, macros, and sensitivity table.
# --------------------------------------------------------------------------- #
def parse_census():
    """Read explicit eligibility and coding fields from the canonical CSV."""
    parsed = []
    for row in csv.DictReader(CENSUS_CSV.open()):
        parsed.append({
            "row_id": row["record_id"],
            "generation": row["generation"],
            "framework": row["framework"],
            "domain": row["domain"],
            "model": row["model"],
            "threshold": row["threshold_text"],
            "n": row["n_text"],
            "n_status": row["n_status"],
            "score": row["score_text"],
            "ci": row["uncertainty_text"],
            "uncertainty_class": row["uncertainty_class"],
            "direction": row["direction"],
            "citation": row["citation"],
            "source_id": row["source_id"],
            "include_primary": row["include_primary"].lower() == "true",
            "exclusion_reason": row["exclusion_reason"],
        })
    return parsed


# --------------------------------------------------------------------------- #
# Cross-reference between the corpus and the model-level audit. Multiple model
# results may map to one source record (A4), which is intentional and explicit.
# We tag the source records and hand each audit result its stable source ID.
# build_census can shade them and hand each a stable ID that build_audit_table
# then prints, making the mapping between the two tables explicit.
# --------------------------------------------------------------------------- #
def audit_capability(row):
    """Return the audit capability slug for an audited corpus record.

    Only Anthropic rows are auditable; the domain text
    varies (``SWE-bench Verified (hard)`` vs ``SWE-bench hard``), so match on the
    domain prefix rather than the exact string."""
    if row["framework"] != "Anthropic":
        return None
    d = row["domain"]
    if d.startswith("Autonomy SWE-bench"):
        return "swebench_hard"
    if d.startswith("Autonomy METR data-dedup"):
        return "metr_dedup"
    if d.startswith("CBRN bioweapons knowledge"):
        return "bioweapons_knowledge"
    return None


def _audited_models():
    """capability -> set of model names actually audited (from audited.csv)."""
    out = {}
    for r in csv.DictReader((DERIVED / "audited.csv").open()):
        out.setdefault(r["capability"], set()).add(r["model"])
    return out


def build_census(parsed):
    included = [r for r in parsed if r["include_primary"]]
    excluded = [r for r in parsed if not r["include_primary"]]
    post = [r for r in included if r["generation"] == "post2025"]

    def counts(rows):
        score_n = sum(r["n_status"] == "score_denominator" for r in rows)
        partial_n = sum(r["n_status"] == "partial_or_indirect" for r in rows)
        no_n = sum(r["n_status"] == "not_reported" for r in rows)
        interval = sum(r["uncertainty_class"] == "proper_interval" for r in rows)
        bare_pm = sum(r["uncertainty_class"] == "bare_dispersion" for r in rows)
        none = sum(r["uncertainty_class"] == "none" for r in rows)
        return {
            "total": len(rows), "with_n": score_n + partial_n,
            "score_n": score_n, "partial_n": partial_n, "no_n": no_n,
            "uncertainty": interval + bare_pm, "interval": interval,
            "bare_pm": bare_pm, "none": none,
        }

    primary_counts = counts(included)
    screened_counts = counts(parsed)

    macros = rf"""% GENERATED by scripts/make_tables.py -- exact census counts.
\newcommand{{\CensusScreened}}{{{screened_counts['total']}}}
\newcommand{{\CensusExcluded}}{{{len(excluded)}}}
\newcommand{{\CensusTotal}}{{{primary_counts['total']}}}
\newcommand{{\CensusWithN}}{{{primary_counts['with_n']}}}
\newcommand{{\CensusScoreN}}{{{primary_counts['score_n']}}}
\newcommand{{\CensusPartialN}}{{{primary_counts['partial_n']}}}
\newcommand{{\CensusNoN}}{{{primary_counts['no_n']}}}
\newcommand{{\CensusUncertainty}}{{{primary_counts['uncertainty']}}}
\newcommand{{\CensusNoUncertainty}}{{{primary_counts['none']}}}
\newcommand{{\CensusInterval}}{{{primary_counts['interval']}}}
\newcommand{{\CensusBarePm}}{{{primary_counts['bare_pm']}}}
\newcommand{{\CensusPostRows}}{{{len(post)}}}
\newcommand{{\LegacyCensusTotal}}{{{screened_counts['total']}}}
\newcommand{{\LegacyCensusWithN}}{{{screened_counts['with_n']}}}
\newcommand{{\LegacyCensusNoUncertainty}}{{{screened_counts['none']}}}
"""
    (TABLES / "census_counts.tex").write_text(macros)

    sensitivity = rf"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{{table}}[t]
    \centering
    \small
    \begin{{tabular}}{{lrrrrrr}}
        \toprule
        coding & records & score $n$ & partial $n$ & no $n$ & any uncertainty & proper interval \\
        \midrule
        Primary eligible corpus & {primary_counts['total']} & {primary_counts['score_n']} & {primary_counts['partial_n']} & {primary_counts['no_n']} & {primary_counts['uncertainty']} & {primary_counts['interval']} \\
        All screened records & {screened_counts['total']} & {screened_counts['score_n']} & {screened_counts['partial_n']} & {screened_counts['no_n']} & {screened_counts['uncertainty']} & {screened_counts['interval']} \\
        \bottomrule
    \end{{tabular}}
    \caption{{Corpus-coding sensitivity. The primary corpus excludes T7 (a benchmark description with no evaluated-model result) and A32 (explicitly not used for the RSP determination). ``score $n$'' is a denominator tied to the displayed score; ``partial $n$'' is numerical sample information that does not identify that denominator. Including both screened-but-ineligible records changes the record count but not the number reporting uncertainty.}}
    \label{{tab:census-sensitivity}}
\end{{table}}
"""
    (TABLES / "census_sensitivity.tex").write_text(sensitivity)

    # Longtable of the primary eligible corpus in stable-ID order.
    audited = _audited_models()
    id_map = {}        # (capability, model) -> census row ID, for the audit table
    body = []
    for r in included:
        display_fw = r["framework"]
        row_id = r["row_id"]

        # Is this one of the audited source records? Match capability + model, where a
        # census cell can bundle models ("Opus 4 / Sonnet 4"); tag the row and
        # register the ID under each audited model it covers.
        cap = audit_capability(r)
        is_audited = False
        if cap is not None:
            audited_here = audited.get(cap, set())
            for m in (t.strip() for t in r["model"].split("/")):
                if m in audited_here:
                    is_audited = True
                    id_map[(cap, m)] = row_id

        prefix = r"\rowcolor{auditrow} " if is_audited else ""
        body.append(
            prefix + "  " + " & ".join([
                row_id,
                display_fw,
                latex_escape(r["domain"]),
                latex_escape(r["model"]),
                latex_escape(r["threshold"]),
                latex_escape(r["n"]),
                latex_escape(r["score"]),
                latex_escape(r["ci"]),
                latex_escape(r["citation"]),
            ]) + r" \\"
        )

    excluded_body = "\n".join(
        "  " + " & ".join([
            r["row_id"], latex_escape(r["framework"]), latex_escape(r["domain"]),
            latex_escape(r["model"]), latex_escape(r["exclusion_reason"]),
        ]) + r" \\" for r in excluded
    )

    tex = r"""% GENERATED by scripts/make_tables.py -- do not edit by hand.
\begin{small}
\begin{longtable}{p{0.7cm}p{1.4cm}p{2.4cm}p{1.5cm}p{2.2cm}p{1.2cm}p{1.7cm}p{1.5cm}p{1.9cm}}
\caption{Primary structured corpus of source-reported dangerous-capability evaluation records, spanning the
Claude~4 / Gemini~2.5 / GPT-4.x generation through the GPT-5.6~Preview card of
June 2026, parsed from \texttt{data/raw/census\_records.csv}. ``uncert.'' reproduces
the source's uncertainty cell verbatim; most rows report none. Each row carries
an ID (framework letter + running number); \colorbox{auditrow}{shaded} rows are
audited in \Cref{sec:audit}, and their IDs appear beside the eval names
in \Cref{tab:audit}.}
\label{tab:census}\\
\toprule
ID & framework & domain & model & threshold & $n$ & score & uncert. & citation \\
\midrule
\endfirsthead
\multicolumn{9}{c}{\tablename\ \thetable\ -- continued}\\
\toprule
ID & framework & domain & model & threshold & $n$ & score & uncert. & citation \\
\midrule
\endhead
\midrule \multicolumn{9}{r}{continued on next page}\\
\endfoot
\bottomrule
\endlastfoot
""" + "\n".join(body) + r"""
\end{longtable}
\end{small}
\paragraph{Screened but excluded records.}
\begin{center}
\begin{small}
\begin{tabular}{llllp{6.2cm}}
\toprule
ID & framework & domain & model & exclusion reason \\
\midrule
""" + excluded_body + r"""
\bottomrule
\end{tabular}
\end{small}
\end{center}
"""
    (TABLES / "census.tex").write_text(tex)
    return {
        **primary_counts, "screened": screened_counts["total"],
        "excluded": len(excluded),
        "post_rows": len(post), "id_map": id_map,
    }


def main():
    TABLES.mkdir(parents=True, exist_ok=True)
    nu = build_uplift_table()
    # Census first: it assigns the row IDs that the audit table cross-references.
    parsed = parse_census()
    cinfo = build_census(parsed)
    na = build_audit_table(cinfo["id_map"])
    print(f"uplift.tex: {nu} reading-rows")
    print(f"audit.tex:  {na} rows")
    print(f"census.tex: {cinfo['total']} included rows ({cinfo['excluded']} excluded; "
          f"{cinfo['post_rows']} included from the post-2025 generation)")
    print(f"census counts (primary): total={cinfo['total']}, "
          f"with n={cinfo['with_n']}, no n={cinfo['no_n']}, "
          f"any uncertainty={cinfo['uncertainty']} "
          f"(proper interval={cinfo['interval']}, bare ±={cinfo['bare_pm']})")
    print(f"wrote tables into {TABLES}")


if __name__ == "__main__":
    main()
